<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_67eea654015f6',
	'title' => 'Advanced Block Options',
	'fields' => array(
		array(
			'key' => 'field_67eea7cfa87ee',
			'label' => 'Block Options',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_67eea65459191',
			'label' => 'Padding Top',
			'name' => 'padding_top',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'' => 'Default',
				0 => 'None',
				'xs' => 'Extra Small',
				'sm' => 'Small',
				'md' => 'Medium',
				'lg' => 'Large',
			),
			'default_value' => '',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_67eea6de59192',
			'label' => 'Padding Bottom',
			'name' => 'padding_bottom',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'' => 'Default',
				0 => 'None',
				'xs' => 'Extra Small',
				'sm' => 'Small',
				'md' => 'Medium',
				'lg' => 'Large',
			),
			'default_value' => '',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_67eea72cf6912',
			'label' => 'Block Theme',
			'name' => 'theme_override',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'sommet' => 'Default',
				'glion-light' => 'Glion Light',
				'glion-blue' => 'Glion Blue',
				'glion-bronze' => 'Glion Bronze',
			),
			'default_value' => 'sommet',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 999,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );